services:
- docker
script:
- docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD 
- docker build --target production --tag $DOCKER_HUB_USER/todo-app:latest .
- docker push $DOCKER_HUB_USER/todo-app:latest



