services:
- docker
script:
- docker build --target test --tag my-test-image .
- docker run my-test-image test_items.py
- docker run my-test-image test_client.py
- docker run my-test-image test_system.py
