services:
- docker
script:
- echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
- docker build --target production --tag $DOCKER_HUB_USER/todo-app:latest .
- docker push $DOCKER_HUB_USER/todo-app:latest



